codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      validation-server:
        target: auto
        threshold: 1%
        flags:
          - validation-server

    patch:
      validation-server:
        target: 80
        threshold: 1%
        base: auto

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches: null
  show_carryforward_flags: false

flags:
  validation-server:
    paths:
      - interop-validation-server/
    carryforward: true
