[libraries]
interop-commonTestDb = "com.projectronin.interop:interop-common-test-db:3.0.1"
jackson-dataformat-xml = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.13.4"
jackson-dataformat-yaml = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.13.4"
jackson-datatype-jsr310 = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.4"
jackson-module-kotlin = "com.fasterxml.jackson.module:jackson-module-kotlin:2.13.4"
jakarta-validation-api = "jakarta.validation:jakarta.validation-api:2.0.2"
ktorm-core = "org.ktorm:ktorm-core:3.5.0"
ktorm-support-mysql = "org.ktorm:ktorm-support-mysql:3.5.0"
liquibase-core = "org.liquibase:liquibase-core:4.16.1"
mockk = "io.mockk:mockk:1.13.2"
mysql-connector-java = "mysql:mysql-connector-java:8.0.30"
rider-core = "com.github.database-rider:rider-core:1.34.0"
springdoc-openapi-ui = "org.springdoc:springdoc-openapi-ui:1.6.11"
spring-boot-parent = "org.springframework.boot:spring-boot-parent:2.7.4"
testcontainers-mysql = "org.testcontainers:mysql:1.17.3"
uuid-creator = "com.github.f4b6a3:uuid-creator:5.1.2"

[bundles]
jackson = ["jackson-dataformat-xml", "jackson-dataformat-yaml", "jackson-datatype-jsr310", "jackson-module-kotlin"]
