[libraries]
interop-common = "com.projectronin.interop:interop-common:3.1.0"
interop-commonHttp = "com.projectronin.interop:interop-common-http:3.1.0"
interop-commonJackson = "com.projectronin.interop:interop-common-jackson:3.1.0"
interop-commonTestDb = "com.projectronin.interop:interop-common-test-db:3.1.0"
interop-fhir = "com.projectronin.interop.fhir:interop-fhir:4.0.1"
jackson-dataformat-xml = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.14.1"
jackson-dataformat-yaml = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.14.1"
jackson-datatype-jsr310 = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.14.1"
jackson-module-kotlin = "com.fasterxml.jackson.module:jackson-module-kotlin:2.14.1"
jakarta-validation-api = "jakarta.validation:jakarta.validation-api:2.0.2"
ktor-client-cio = "io.ktor:ktor-client-cio:2.1.3"
ktor-client-content-negotiation = "io.ktor:ktor-client-content-negotiation:2.1.3"
ktor-client-core = "io.ktor:ktor-client-core:2.1.3"
ktor-serialization-jackson = "io.ktor:ktor-serialization-jackson:2.1.3"
ktorm-core = "org.ktorm:ktorm-core:3.5.0"
ktorm-support-mysql = "org.ktorm:ktorm-support-mysql:3.5.0"
liquibase-core = "org.liquibase:liquibase-core:4.18.0"
mockk = "io.mockk:mockk:1.13.3"
mockwebserver = "com.squareup.okhttp3:mockwebserver:4.10.0"
mysql-connector-java = "mysql:mysql-connector-java:8.0.31"
rider-core = "com.github.database-rider:rider-core:1.35.0"
springdoc-openapi-ui = "org.springdoc:springdoc-openapi-ui:1.6.13"
spring-boot-parent = "org.springframework.boot:spring-boot-parent:2.7.5"
spring-boot-actuator = "org.springframework.boot:spring-boot-starter-actuator:2.7.5"
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.17.6"
uuid-creator = "com.github.f4b6a3:uuid-creator:5.2.0"

[bundles]
jackson = ["jackson-dataformat-xml", "jackson-dataformat-yaml", "jackson-datatype-jsr310", "jackson-module-kotlin"]
ktor = ["ktor-client-cio", "ktor-client-content-negotiation", "ktor-client-core", "ktor-serialization-jackson"]
