[libraries]
interop-commonTestDb = "com.projectronin.interop:interop-common-test-db:2.1.1"
ktorm-core = "org.ktorm:ktorm-core:3.5.0"
ktorm-support-mysql = "org.ktorm:ktorm-support-mysql:3.5.0"
liquibase-core = "org.liquibase:liquibase-core:4.15.0"
mockk = "io.mockk:mockk:1.12.5"
mysql-connector-java = "mysql:mysql-connector-java:8.0.30"
rider-core = "com.github.database-rider:rider-core:1.32.3"
spring-boot-parent = "org.springframework.boot:spring-boot-parent:2.7.2"
springdoc-openapi-ui = "org.springdoc:springdoc-openapi-ui:1.6.9"
testcontainers-mysql = "org.testcontainers:mysql:1.17.3"
uuid-creator = "com.github.f4b6a3:uuid-creator:5.1.0"
