name: PROD - Deploy to ArgoCD
run-name: Build and deploy to PROD by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: tag of the image to deploy
        required: true
        type: string

jobs:
  argocd_prod:
    uses: projectronin/github/.github/workflows/argocd_deploy.yml@master
    with:
      environment: prod
      image-tag: ${{ inputs.image_tag }}
    secrets:
      argocd-svc-automation: ${{ secrets.ARGOCD_SVC_AUTOMATION }}

  tag_prod_deploy:
    uses: projectronin/github/.github/workflows/tag_commit_w_stamp.yml@tag_commit_w_stamp/v2
    needs: [ argocd_prod ]
    with:
      deploy-env: prod
      commit-sha: ${{ inputs.image_tag }}
